[package]
name = "migrator"
version.workspace = true
edition.workspace = true

[dependencies]
clap = { workspace = true }
chrono = { workspace = true }
store = { path = "../store" }
tokio = { workspace = true, features = ["macros"] }
types = { path = "../types" }
